name: Generate pacman animation

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3

      - name: Generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Checkout output branch
        uses: actions/checkout@v3
        with:
          ref: output
          clean: false

      - name: Copy generated file to pacman/
        run: |
          mkdir -p pacman
          cp dist/pacman-contribution-graph.svg pacman/

      - name: Commit & Push to output branch
        uses: EndBug/add-and-commit@v9
        with:
          add: "pacman/*"
          message: "Update pacman graph"
          default_author: github_actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
